import { useEffect, useState } from 'react'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'

import type { PersistentMutationResult, PersistentSlotReadModel } from '../api/models'
import type { FleetInstanceView } from '../fleet/types'
import { useI18n } from '../i18n/useI18n'
import { serverRoute, slotRoute, slotsRoute, taskRoute } from '../navigation/routes'

export type PersistentMutator = (instanceId: string, path: string, body: Record<string, unknown>) => Promise<PersistentMutationResult>
const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
function idempotencyKey(): string { return globalThis.crypto?.randomUUID ? globalThis.crypto.randomUUID() : `console-${Date.now()}-${Math.random().toString(36).slice(2)}` }
function randomSelector(): string { const bytes = new Uint8Array(4); globalThis.crypto?.getRandomValues?.(bytes); return Array.from(bytes, (value, index) => CROCKFORD[(value || (Date.now() >> index)) % CROCKFORD.length]).join('') }
function duration(seconds: number): string { const safe = Math.max(0, Math.floor(seconds)); const minutes = Math.floor(safe / 60); const rest = safe % 60; return minutes > 0 ? `${minutes}m ${rest}s` : `${rest}s` }
function slotTiming(slot: PersistentSlotReadModel, authorityNowMs: number, durationSeconds: number, warningAfter: number, alertAfter: number) { if (!slot.workSession) return { text: slot.state, cue: 'normal' as const }; const remaining = Math.max(0, Math.floor((Date.parse(slot.workSession.hardExpiresAt) - authorityNowMs) / 1000)); const elapsed = Math.max(0, durationSeconds - remaining); const cue = elapsed >= alertAfter ? 'alert' as const : elapsed >= warningAfter ? 'warning' as const : 'normal' as const; return { text: duration(remaining), cue } }

export function ServerSlots({ instances, mutatePersistent }: { instances: FleetInstanceView[]; mutatePersistent?: PersistentMutator }) {
  const { t } = useI18n(); const { instanceId = '', logicalAgentId } = useParams(); const navigate = useNavigate()
  const instance = instances.find((item) => item.profile.instanceId === instanceId); const persistent = instance?.runtime.realtime?.snapshot?.persistent; const slots = persistent?.slots ?? []; const selected = logicalAgentId ? slots.find((slot) => slot.logicalAgentId === logicalAgentId) : undefined
  const [clock, setClock] = useState(() => Date.now()); const [anchor, setAnchor] = useState(() => ({ server: '', serverMs: Date.now(), localMs: Date.now() })); const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [createName, setCreateName] = useState(''); const [reassignTarget, setReassignTarget] = useState('')
  const [policyDraft, setPolicyDraft] = useState<{ key: string; duration: string; warning: string; alert: string } | null>(null)
  const serverNow = persistent?.serverNow ?? slots[0]?.serverNow ?? ''
  useEffect(() => {
    if (!serverNow || serverNow === anchor.server) return
    const timer = window.setTimeout(() => {
      setAnchor({ server: serverNow, serverMs: Date.parse(serverNow), localMs: Date.now() })
    }, 0)
    return () => window.clearTimeout(timer)
  }, [anchor.server, serverNow])
  useEffect(() => { const timer = window.setInterval(() => setClock(Date.now()), 1000); return () => window.clearInterval(timer) }, [])
  const authorityNowMs = anchor.server ? anchor.serverMs + (clock - anchor.localMs) : clock
  const policyKey = persistent ? `${persistent.policy.durationSeconds}:${persistent.policy.warningAfterSeconds}:${persistent.policy.alertAfterSeconds}` : ''
  const draft = policyDraft?.key === policyKey ? policyDraft : { key: policyKey, duration: String(persistent?.policy.durationSeconds ?? ''), warning: String(persistent?.policy.warningAfterSeconds ?? ''), alert: String(persistent?.policy.alertAfterSeconds ?? '') }
  const canMutate = Boolean(mutatePersistent && persistent?.enabled && persistent.available && instance?.runtime.authStatus === 'connected' && instance.runtime.status === 'live')
  const mutation = async (key: string, path: string, body: Record<string, unknown>) => { if (!canMutate || !mutatePersistent) { setMessage(t('slots.liveRequired')); return false } setBusy(key); setMessage(''); try { const result = await mutatePersistent(instanceId, path, body); if (!result.ok) { setMessage(result.code ?? result.error ?? t('slots.mutationFailed')); return false } setMessage(t('slots.mutationApplied')); return true } catch (error) { setMessage(error instanceof Error ? error.message : t('slots.mutationFailed')); return false } finally { setBusy('') } }
  const mutateSlot = (slot: PersistentSlotReadModel, action: 'play' | 'suspend' | 'delete') => mutation(`${slot.logicalAgentId}:${action}`, `/actions/persistent/slots/${action}`, { logical_agent_id: slot.logicalAgentId, expected_revision: slot.slotRevision, idempotency_key: idempotencyKey() })
  const rotate = (slot: PersistentSlotReadModel) => mutation(`${slot.logicalAgentId}:rotate`, '/actions/persistent/slots/rotate-selector', { logical_agent_id: slot.logicalAgentId, selector: randomSelector(), expected_revision: slot.slotRevision, idempotency_key: idempotencyKey() })
  const timingPolicyLocked = slots.some((slot) => ['armed', 'active', 'stopping'].includes(slot.state))
  const saveTimingPolicy = async () => {
    const durationSeconds = Number(draft.duration); const warningAfterSeconds = Number(draft.warning); const alertAfterSeconds = Number(draft.alert)
    if (![durationSeconds, warningAfterSeconds, alertAfterSeconds].every(Number.isInteger) || !(0 < warningAfterSeconds && warningAfterSeconds < alertAfterSeconds && alertAfterSeconds < durationSeconds)) {
      setMessage(t('slots.policyInvalid')); return
    }
    await mutation('policy', '/actions/persistent/policy', { duration_seconds: durationSeconds, warning_after_seconds: warningAfterSeconds, alert_after_seconds: alertAfterSeconds })
  }
  const toggleLegacy = async () => {
    if (!persistent) return
    await mutation('legacy-policy', '/actions/persistent/policy', { legacy_admission_enabled: !persistent.policy.legacyAdmissionEnabled })
  }
  const activeSession = selected?.workSession
  const otherSlots = slots.filter(
    (slot) => slot.logicalAgentId !== selected?.logicalAgentId && slot.state !== 'deleted',
  )
  if (!instance) return <Navigate to="/" replace />
  const copySelector = async (selector: string) => { try { await navigator.clipboard.writeText(selector); setMessage(t('slots.selectorCopied')) } catch { setMessage(t('slots.copyFailed')) } }
  return <section className="stack" aria-labelledby="slots-title">
    <div className="page-heading"><div><p className="eyebrow">{instance.profile.displayName}</p><h2 id="slots-title">{t('nav.slots')}</h2><p className="muted">{t('slots.description')}</p></div><div className="page-tools"><label className="server-switcher"><span>{t('server.switch')}</span><select aria-label={t('aria.switchServer')} value={instanceId} onChange={(event) => navigate(slotsRoute(event.target.value))}>{instances.map((item) => <option key={item.profile.instanceId} value={item.profile.instanceId}>{item.profile.displayName}</option>)}</select></label><span className={'status status-' + instance.runtime.status}>{instance.runtime.status}</span></div></div>
    {instance.runtime.status !== 'live' && <div className="attention-strip" role="status">{t('slots.cachedReadOnly')} {instance.runtime.status}.</div>}
    {persistent && !persistent.enabled && <article className="panel"><p>{t('slots.disabled')}</p></article>}
    {persistent?.enabled && !persistent.available && <article className="panel"><p>{t('slots.unavailable')} {persistent.error ?? ''}</p></article>}
    {message && <div className="attention-strip" role="status"><span>{message}</span></div>}
    {persistent?.enabled && persistent.available && persistent.policy.policyControlSupported && <article className="panel policy-controls"><div className="section-heading"><div><p className="eyebrow">{t('slots.policy')}</p><h3>{t('slots.policyControls')}</h3></div></div><div className="policy-controls-grid"><label><span>{t('slots.durationSeconds')}</span><input aria-label={t('slots.durationSeconds')} inputMode="numeric" type="number" min="1" value={draft.duration} onChange={(event) => setPolicyDraft({ ...draft, duration: event.target.value })} disabled={!canMutate || Boolean(busy) || timingPolicyLocked} /></label><label><span>{t('slots.warningAfterSeconds')}</span><input aria-label={t('slots.warningAfterSeconds')} inputMode="numeric" type="number" min="1" value={draft.warning} onChange={(event) => setPolicyDraft({ ...draft, warning: event.target.value })} disabled={!canMutate || Boolean(busy) || timingPolicyLocked} /></label><label><span>{t('slots.alertAfterSeconds')}</span><input aria-label={t('slots.alertAfterSeconds')} inputMode="numeric" type="number" min="1" value={draft.alert} onChange={(event) => setPolicyDraft({ ...draft, alert: event.target.value })} disabled={!canMutate || Boolean(busy) || timingPolicyLocked} /></label></div><div className="server-actions"><button type="button" disabled={!canMutate || Boolean(busy) || timingPolicyLocked} onClick={() => void saveTimingPolicy()}>{t('slots.savePolicy')}</button></div>{timingPolicyLocked && <p className="muted">{t('slots.policyLocked')}</p>}<label className="policy-toggle"><input aria-label={t('slots.legacyToggle')} type="checkbox" checked={persistent.policy.legacyAdmissionEnabled} disabled={!canMutate || Boolean(busy)} onChange={() => void toggleLegacy()} /><span><strong>{t('slots.legacyToggle')}</strong><small>{t('slots.legacyHint')}</small></span></label></article>}
    {persistent?.enabled && persistent.available && <form className="slot-create panel" onSubmit={(event) => { event.preventDefault(); const displayName = createName.trim(); if (!displayName) return; void mutation('create', '/actions/persistent/slots/create', { display_name: displayName }).then((ok) => { if (ok) setCreateName('') }) }}><label><span>{t('slots.createName')}</span><input value={createName} onChange={(event) => setCreateName(event.target.value)} maxLength={120} /></label><button type="submit" disabled={!canMutate || busy === 'create'}>{t('slots.create')}</button></form>}
    {selected && persistent && <article className="panel slot-detail" aria-label={t('title.slotDetail')}><div className="section-heading"><div><p className="eyebrow">{t('slots.logicalAgent')}</p><h3>{selected.displayName}</h3></div><span className="chip">{selected.state}</span></div><dl className="slot-details-grid"><div><dt>{t('slots.logicalAgent')}</dt><dd><code>{selected.logicalAgentId}</code></dd></div><div><dt>{t('slots.selector')}</dt><dd><code>{selected.selector}</code></dd></div><div><dt>{t('slots.selectorGeneration')}</dt><dd>{selected.selectorGeneration}</dd></div><div><dt>{t('slots.authGeneration')}</dt><dd>{selected.authGeneration}</dd></div><div><dt>{t('slots.authority')}</dt><dd>{selected.authorityNodeId} · e{selected.authorityEpoch}</dd></div><div><dt>{t('slots.revision')}</dt><dd>{selected.slotRevision}</dd></div><div><dt>{t('slots.session')}</dt><dd>{activeSession ? <code>{activeSession.workSessionId}</code> : t('slots.noSession')}</dd></div><div><dt>{t('slots.sessionEpoch')}</dt><dd>{activeSession?.sessionEpoch ?? '—'}</dd></div><div><dt>{t('slots.hardExpiresAt')}</dt><dd>{activeSession?.hardExpiresAt ?? '—'}</dd></div><div><dt>{t('slots.policy')}</dt><dd>D {duration(persistent.policy.durationSeconds)} · W {duration(persistent.policy.warningAfterSeconds)} · A {duration(persistent.policy.alertAfterSeconds)}</dd></div><div><dt>{t('slots.manualRearm')}</dt><dd>{persistent.policy.manualRearm ? t('slots.yes') : t('slots.no')}</dd></div><div><dt>{t('slots.admissionMode')}</dt><dd>{persistent.policy.admissionMode}</dd></div><div><dt>{t('slots.legacyAdmission')}</dt><dd>{persistent.policy.legacyAdmissionEnabled ? t('slots.yes') : t('slots.no')}</dd></div><div><dt>{t('slots.createdAt')}</dt><dd>{selected.createdAt}</dd></div><div><dt>{t('slots.updatedAt')}</dt><dd>{selected.updatedAt}</dd></div></dl><div className="server-actions"><button type="button" onClick={() => void copySelector(selected.selector)}>{t('slots.copySelector')}</button><button type="button" disabled={!canMutate || Boolean(busy) || ['active','stopping','deleting','deleted'].includes(selected.state)} onClick={() => void rotate(selected)}>{t('slots.rotateSelector')}</button></div>
      <div className="slot-subsection"><h3>{t('slots.claims')}</h3>{selected.claims.length ? selected.claims.map((claim) => <div className="slot-claim" key={`${claim.namespace}/${claim.taskId}`}><Link className="text-link" to={taskRoute(instanceId, claim.namespace, claim.taskId)}>{claim.namespace}/{claim.taskId}</Link><span>{claim.priority} · {claim.state}</span>{activeSession && <div className="server-actions"><button type="button" disabled={!canMutate || Boolean(busy)} onClick={() => void mutation(`release:${claim.namespace}/${claim.taskId}`, '/actions/persistent/claims/release', { namespace: claim.namespace, task_id: claim.taskId, logical_agent_id: selected.logicalAgentId, work_session_id: activeSession.workSessionId, session_epoch: activeSession.sessionEpoch })}>{t('slots.releaseClaim')}</button>{otherSlots.length > 0 && <><select aria-label={t('slots.reassignTarget')} value={reassignTarget} onChange={(event) => setReassignTarget(event.target.value)}><option value="">{t('slots.chooseTarget')}</option>{otherSlots.map((slot) => <option key={slot.logicalAgentId} value={slot.logicalAgentId}>{slot.displayName}</option>)}</select><button type="button" disabled={!canMutate || !reassignTarget || Boolean(busy)} onClick={() => void mutation(`reassign:${claim.namespace}/${claim.taskId}`, '/actions/persistent/claims/reassign', { namespace: claim.namespace, task_id: claim.taskId, logical_agent_id: selected.logicalAgentId, to_logical_agent_id: reassignTarget, work_session_id: activeSession.workSessionId, session_epoch: activeSession.sessionEpoch, expected_revision: selected.slotRevision, idempotency_key: idempotencyKey() })}>{t('slots.reassignClaim')}</button></>}</div>}</div>) : <p className="muted">{t('slots.noClaims')}</p>}</div>
      <div className="slot-subsection"><h3>{t('slots.fleet')}</h3>{selected.attachments.length ? selected.attachments.map((attachment) => <p key={attachment.nodeAttachmentId}>{attachment.nodeInstanceId} · <code>{attachment.nodeAttachmentId}</code></p>) : <p className="muted">{t('slots.noAttachments')}</p>}</div><div className="slot-subsection"><h3>{t('slots.audit')}</h3>{selected.audit.length ? <ul className="slot-audit">{selected.audit.map((entry) => <li key={entry.id}><strong>{entry.eventType}</strong><span>{entry.createdAt}</span><code>{entry.principalId}</code></li>)}</ul> : <p className="muted">{t('slots.noAudit')}</p>}</div><Link className="nav-link" to={slotsRoute(instanceId)}>{t('slots.backToSlots')}</Link></article>}
    <div className="slot-grid">{slots.map((slot) => { const timing = slotTiming(slot, authorityNowMs, persistent?.policy.durationSeconds ?? 0, persistent?.policy.warningAfterSeconds ?? 0, persistent?.policy.alertAfterSeconds ?? 0); const active = slot.state === 'active'; const suspended = slot.state === 'suspended'; const mutable = !['stopping','deleting','deleted'].includes(slot.state); return <article className={`panel slot-card slot-cue-${timing.cue}`} key={slot.logicalAgentId}><div className="section-heading"><Link className="text-link" to={slotRoute(instanceId, slot.logicalAgentId)}>{slot.displayName}</Link><span className="chip">{slot.state}</span></div><div className="slot-selector"><code>{slot.selector}</code><button type="button" onClick={() => void copySelector(slot.selector)}>{t('slots.copy')}</button></div><p className="slot-time" role={timing.cue === 'normal' ? undefined : 'status'}><strong>{timing.cue === 'alert' ? t('slots.alert') : timing.cue === 'warning' ? t('slots.warning') : t('slots.time')}</strong> {timing.text}</p><div className="server-actions">{suspended ? <button type="button" disabled={!canMutate || Boolean(busy)} onClick={() => void mutateSlot(slot, 'play')}>{t('slots.play')}</button> : mutable ? <button type="button" disabled={!canMutate || Boolean(busy)} onClick={() => void mutateSlot(slot, 'suspend')}>{active ? t('slots.suspend') : t('slots.cancelArm')}</button> : null}<button type="button" disabled={!canMutate || Boolean(busy) || active || !mutable} onClick={() => { if (window.confirm(t('slots.deleteConfirm'))) void mutateSlot(slot, 'delete') }}>{t('slots.delete')}</button><Link className="nav-link" to={slotRoute(instanceId, slot.logicalAgentId)}>{t('slots.details')}</Link></div></article> })}{persistent?.enabled && persistent.available && slots.length === 0 && <article className="panel"><p className="muted">{t('slots.empty')}</p></article>}</div>
    <div className="server-actions"><Link className="nav-link" to={serverRoute(instanceId)}>{t('nav.backToServer')}</Link></div>
  </section>
}
