from typing import Protocol

from .models import Command, Line


class CommandRepository(Protocol):
    async def initialize(self) -> None: ...
    async def create(self, cmd: str) -> Command: ...
    async def update(self, command: Command) -> None: ...
    async def get(self, cmd_hash: str) -> Command | None: ...
    async def append_line(self, cmd_hash: str, text: str) -> None: ...
    async def read_lines(self, cmd_hash: str | None, limit: int, offset: int) -> list[Line]: ...


class TerminalAdapter(Protocol):
    async def submit(self, command: Command) -> None: ...
    async def cancel(self, command: Command) -> bool: ...
    async def health(self) -> dict: ...
