from typing import Protocol, runtime_checkable

from .models import Command, Line


class CommandRepository(Protocol):
    async def initialize(self) -> None: ...
    async def create(self, cmd: str) -> Command: ...
    async def update(self, command: Command) -> None: ...
    async def get(self, cmd_hash: str) -> Command | None: ...
    async def append_line(self, cmd_hash: str, text: str) -> None: ...
    async def read_lines(self, cmd_hash: str | None, limit: int, offset: int) -> list[Line]: ...


@runtime_checkable
class CommandSchedulerPort(Protocol):
    """Application-owned command lifecycle, separate from the process-only port."""

    queue_workers: int

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def submit(self, command: Command) -> None: ...
    async def cancel(
        self, command: Command, timeout_seconds: float = 10
    ) -> tuple[bool, str | None]: ...
    async def recovery(self, command: Command, timeout_seconds: float = 20) -> int: ...
    async def finalize_running(
        self, command: Command, status: str, exit_code=None, error=None
    ) -> bool: ...
    async def least_loaded_queue(self) -> int: ...
    async def health(self) -> dict: ...
    async def capture(
        self,
        command: str,
        timeout_ms: int = 5000,
        max_output_lines: int = 1000,
        timeout_error: str = "capture timed out",
    ) -> dict: ...
    def owns_command(self, command_hash: str) -> bool: ...
    def owns_pending(self, command: Command) -> bool: ...
    def cancel_pending(self, command_hash: str) -> None: ...
    async def process_exists(self, pid: int) -> bool: ...


# Source compatibility for callers importing the previous, incomplete name.
TerminalAdapter = CommandSchedulerPort
